/**
 * Formatting helpers shared by the screens. Compact on purpose: a terminal row has 80 cells,
 * so tokens read `4.2k` here where the printed report says `4 200` (`../format.ts`, which the
 * shareable summary and `moldig audit` keep using).
 *
 * Everything is pure and platform-aware (`~`-shortening and basenames respect `\` on win32).
 */
import type { Category, TokenRange } from "@moldig/core";

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const kb = bytes / 1024;
  if (kb < 1024) return `${Math.round(kb)} KB`;
  const mb = kb / 1024;
  if (mb < 1024) return `${mb < 10 ? mb.toFixed(1) : Math.round(mb)} MB`;
  return `${(mb / 1024).toFixed(1)} GB`;
}

/** Always in MB: the two-number header compares like with like (npkill's pattern). */
export function formatMb(bytes: number): string {
  const mb = bytes / (1024 * 1024);
  if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`;
  return mb >= 100 ? `${Math.round(mb)} MB` : `${mb.toFixed(1)} MB`;
}

export function formatTokens(n: number): string {
  if (n < 1000) return String(Math.round(n));
  if (n < 100_000) return `${(n / 1000).toFixed(1)}k`;
  return `${Math.round(n / 1000)}k`;
}

export function formatRange(range: TokenRange): string {
  return `${formatTokens(range.low)}–${formatTokens(range.high)}`;
}

export function formatAge(days: number | null): string {
  if (days === null) return "—";
  if (days === 0) return "today";
  if (days === 1) return "1 day";
  if (days < 60) return `${days} days`;
  return `${Math.round(days / 30)} months`;
}

export function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** `~` for the home directory; separator-aware so win32 labels stay right. */
export function shortPath(path: string, home: string, platform: string): string {
  if (path === home) return "~";
  const sep = platform === "win32" ? "\\" : "/";
  if (path.startsWith(home + sep) || path.startsWith(`${home}/`))
    return `~${path.slice(home.length)}`;
  return path;
}

export function basenameOf(path: string, platform: string): string {
  const parts = path.split(platform === "win32" ? /[\\/]/u : "/").filter(Boolean);
  return parts.at(-1) ?? path;
}

export function truncate(text: string, width: number): string {
  if (width <= 0) return "";
  if (text.length <= width) return text;
  return width <= 1 ? "…" : `${text.slice(0, width - 1)}…`;
}

export function pad(text: string, width: number): string {
  const fitted = truncate(text, width);
  return fitted + " ".repeat(Math.max(0, width - fitted.length));
}

export const SEVERITY_COLOR: Readonly<Record<"low" | "medium" | "high", string>> = {
  low: "green",
  medium: "yellow",
  high: "red",
};

/** The `Category` enum order of index v0; the glossary spells two of them with a space. */
export const CATEGORIES: readonly Category[] = [
  "duplicate",
  "orphan",
  "bloat",
  "drift",
  "shadow-memory",
  "autogenerated",
  "harness-cache",
  "exposure",
];

export const CATEGORY_LABEL: Readonly<Record<Category, string>> = {
  duplicate: "duplicate",
  orphan: "orphan",
  bloat: "bloat",
  drift: "drift",
  "shadow-memory": "shadow memory",
  autogenerated: "autogenerated",
  "harness-cache": "harness cache",
  exposure: "exposure",
};

export function categoryLabel(category: Category): string {
  return CATEGORY_LABEL[category] ?? category;
}
