// THROWAWAY PROTOTYPE (ticket 09) — formatting helpers shared by the Ink screens.
import type { TokenRange } from "@moldig/core";

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  const kb = bytes / 1024;
  if (kb < 1024) return `${Math.round(kb)} KB`;
  const mb = kb / 1024;
  if (mb < 1024) return `${mb < 10 ? mb.toFixed(1) : Math.round(mb)} MB`;
  return `${(mb / 1024).toFixed(1)} GB`;
}

/** Always in MB: the two-number header compares like with like. */
export function formatMb(bytes: number): string {
  const mb = bytes / (1024 * 1024);
  if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`;
  return mb >= 100 ? `${Math.round(mb)} MB` : `${mb.toFixed(1)} MB`;
}

export function formatTokens(n: number): string {
  if (n < 1000) return String(Math.round(n));
  if (n < 100_000) return `${(n / 1000).toFixed(1)}k`;
  return `${Math.round(n / 1000)}k`;
}

export function formatRange(r: TokenRange): string {
  return `${formatTokens(r.low)}–${formatTokens(r.high)}`;
}

export function formatAge(days: number | null): string {
  if (days === null) return "—";
  if (days === 0) return "today";
  if (days === 1) return "1 day";
  if (days < 60) return `${days} days`;
  return `${Math.round(days / 30)} months`;
}

export function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** `~` for the home directory; separator-aware so win32 labels stay right. */
export function shortPath(p: string, home: string, platform: string): string {
  if (p === home) return "~";
  const sep = platform === "win32" ? "\\" : "/";
  if (p.startsWith(home + sep) || p.startsWith(`${home}/`)) return `~${p.slice(home.length)}`;
  return p;
}

export function basenameOf(p: string, platform: string): string {
  const parts = p.split(platform === "win32" ? /[\\/]/ : "/").filter(Boolean);
  return parts.at(-1) ?? p;
}

export function truncate(s: string, width: number): string {
  if (width <= 0) return "";
  if (s.length <= width) return s;
  return width <= 1 ? "…" : `${s.slice(0, width - 1)}…`;
}

export function pad(s: string, width: number): string {
  const t = truncate(s, width);
  return t + " ".repeat(Math.max(0, width - t.length));
}

export const SEVERITY_COLOR: Record<"low" | "medium" | "high", string> = {
  low: "green",
  medium: "yellow",
  high: "red",
};

export const CATEGORY_LABEL: Record<string, string> = {
  duplicate: "duplicate",
  orphan: "orphan",
  bloat: "bloat",
  drift: "drift",
  "shadow-memory": "shadow memory",
  autogenerated: "autogenerated",
  "harness-cache": "harness cache",
  exposure: "exposure",
};

export const CATEGORIES = [
  "duplicate",
  "orphan",
  "bloat",
  "drift",
  "shadow-memory",
  "autogenerated",
  "harness-cache",
  "exposure",
] as const;
