/**
 * The argument parser: hand-written, no dependency of any kind (D13). It is pure — no
 * filesystem, no `process` — so `runCli` can decide what a bad Root or an unsupported platform
 * means (both usage errors, D23/D125) without the parser reaching for either.
 *
 * Shape: `moldig [command] [roots…] [flags]`. The command is the first positional argument when
 * it spells one; everything else positional is a Root. After `--` every argument is a Root, so a
 * directory called `scan` is reachable as `moldig -- scan`.
 */
import { HARNESSES } from "@moldig/core";
import type { Category, HarnessId } from "@moldig/core";

export type CommandName = "default" | "scan" | "audit" | "clean" | "purge" | "update";
export type Severity = "low" | "medium" | "high";
export type FailOn = Severity | "never";

/** The glossary's order, which is also the display order of the categories (D85). */
export const CATEGORIES = [
  "duplicate",
  "orphan",
  "bloat",
  "drift",
  "shadow-memory",
  "autogenerated",
  "harness-cache",
  "exposure",
] as const satisfies readonly Category[];

const SEVERITIES = ["low", "medium", "high"] as const;
const FAIL_ON = ["low", "medium", "high", "never"] as const;
const COMMANDS = ["scan", "audit", "clean", "purge", "update"] as const;

export interface Options {
  command: CommandName;
  /** Verbatim, still relative to the working directory: `runCli` resolves and checks them. */
  roots: string[];
  json: boolean;
  pretty: boolean;
  harnesses: HarnessId[];
  git: boolean;
  readSignal: boolean;
  failOn: FailOn;
  categories: Category[];
  severity: Severity | null;
  olderThanDays: number | null;
  yes: boolean;
  dryRun: boolean;
  help: boolean;
  version: boolean;
}

export type ParseResult = { ok: true; options: Options } | { ok: false; message: string };

/** Flags every command takes (spec § "Shared flags"). */
const SHARED = ["--json", "--pretty", "--harness", "--no-git", "--help", "-h", "--version", "-V"];

/** Flags that take a value; the rest are booleans. */
const NEEDS_VALUE = new Set(["--harness", "--category", "--severity", "--fail-on", "--older-than"]);

/** What each command adds to the shared set (spec § "Command surface"). */
const EXTRA: Record<CommandName, readonly string[]> = {
  default: ["--no-read-signal"],
  scan: [],
  audit: ["--no-read-signal", "--fail-on", "--category", "--severity"],
  clean: ["--no-read-signal", "--dry-run", "--yes", "--category", "--older-than"],
  purge: [],
  update: [],
};

interface Flag {
  name: string;
  value: string | null;
}

function isCommand(value: string): value is Exclude<CommandName, "default"> {
  return (COMMANDS as readonly string[]).includes(value);
}

function oneOf<T extends string>(
  values: readonly T[],
  raw: string,
  flag: string,
): { ok: true; value: T } | { ok: false; message: string } {
  const value = values.find((candidate) => candidate === raw);
  if (value !== undefined) return { ok: true, value };
  return { ok: false, message: `${flag} accepts ${values.join(", ")}, not "${raw}"` };
}

export function parseArgs(argv: readonly string[]): ParseResult {
  const flags: Flag[] = [];
  const positional: string[] = [];
  /** Only a positional that came before `--` can be the command, so `moldig -- scan` is a Root. */
  let commandReachable = true;
  let endOfFlags = false;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i] ?? "";
    if (endOfFlags || !arg.startsWith("-") || arg === "-") {
      positional.push(arg);
      continue;
    }
    if (arg === "--") {
      endOfFlags = true;
      if (positional.length === 0) commandReachable = false;
      continue;
    }
    const eq = arg.indexOf("=");
    const name = eq === -1 ? arg : arg.slice(0, eq);
    const inline = eq === -1 ? null : arg.slice(eq + 1);
    if (!SHARED.includes(name) && !Object.values(EXTRA).some((list) => list.includes(name))) {
      return { ok: false, message: `unknown flag ${name}` };
    }
    if (!NEEDS_VALUE.has(name)) {
      if (inline !== null) return { ok: false, message: `${name} takes no value` };
      flags.push({ name, value: null });
      continue;
    }
    const next = argv[i + 1];
    if (inline === null && (next === undefined || next.startsWith("-"))) {
      return { ok: false, message: `${name} needs a value` };
    }
    if (inline === null) i += 1;
    flags.push({ name, value: inline ?? next ?? "" });
  }

  const first = positional[0];
  const command: CommandName =
    commandReachable && first !== undefined && isCommand(first) ? first : "default";
  const roots = command === "default" ? positional : positional.slice(1);

  const options: Options = {
    command,
    roots,
    json: false,
    pretty: false,
    harnesses: [],
    git: true,
    readSignal: true,
    failOn: "low",
    categories: [],
    severity: null,
    olderThanDays: null,
    yes: false,
    dryRun: false,
    help: false,
    version: false,
  };

  const allowed = new Set(
    command === "purge" || command === "update"
      ? ["--no-git", "--help", "-h", "--version", "-V"]
      : [...SHARED, ...EXTRA[command]],
  );
  for (const { name, value } of flags) {
    if (!allowed.has(name)) {
      return {
        ok: false,
        message:
          command === "default"
            ? `${name} is a flag of ${commandsWith(name).join(" and ")}, not of moldig without a command`
            : `${name} is not a flag of ${command}`,
      };
    }
    switch (name) {
      case "--json": {
        options.json = true;
        break;
      }
      case "--pretty": {
        options.pretty = true;
        options.json = true; // D23
        break;
      }
      case "--no-git": {
        options.git = false;
        break;
      }
      case "--no-read-signal": {
        options.readSignal = false;
        break;
      }
      case "--yes": {
        options.yes = true;
        break;
      }
      case "--dry-run": {
        options.dryRun = true;
        break;
      }
      case "--help":
      case "-h": {
        options.help = true;
        break;
      }
      case "--version":
      case "-V": {
        options.version = true;
        break;
      }
      case "--harness": {
        const id = oneOf(HARNESSES, value ?? "", "--harness");
        if (!id.ok) return { ok: false, message: id.message };
        if (!options.harnesses.includes(id.value)) options.harnesses.push(id.value);
        break;
      }
      case "--category": {
        const category = oneOf(CATEGORIES, value ?? "", "--category");
        if (!category.ok) return { ok: false, message: category.message };
        // D16: an unattended clean reaches harness cache and nothing else in v1.
        if (command === "clean" && category.value !== "harness-cache") {
          return { ok: false, message: "clean --category accepts harness-cache only in v1" };
        }
        if (!options.categories.includes(category.value)) options.categories.push(category.value);
        break;
      }
      case "--severity": {
        const severity = oneOf(SEVERITIES, value ?? "", "--severity");
        if (!severity.ok) return { ok: false, message: severity.message };
        options.severity = severity.value;
        break;
      }
      case "--fail-on": {
        const failOn = oneOf(FAIL_ON, value ?? "", "--fail-on");
        if (!failOn.ok) return { ok: false, message: failOn.message };
        options.failOn = failOn.value;
        break;
      }
      case "--older-than": {
        const days = Number(value);
        if (!Number.isFinite(days) || days < 0) {
          return { ok: false, message: `--older-than accepts a number of days, not "${value}"` };
        }
        options.olderThanDays = days;
        break;
      }
      default: {
        return { ok: false, message: `unknown flag ${name}` };
      }
    }
  }
  return { ok: true, options };
}

function commandsWith(flag: string): string[] {
  return COMMANDS.filter((command) => EXTRA[command].includes(flag));
}

/** `low < medium < high`; `--severity <s>` keeps that severity and above (D132). */
export function severityRank(severity: Severity): number {
  return SEVERITIES.indexOf(severity);
}
