/**
 * `--help` (global and per command) and the one-line usage synopsis a usage error prints
 * (D13; spec § "Usage errors print one line on stderr and the usage synopsis, exit 2").
 * Every user-visible word here comes from the glossary.
 */
import type { CommandName } from "./args.js";

const SYNOPSIS = "usage: moldig [scan|audit|clean|purge|update] [roots…] [flags]   (moldig --help)";

export function usageSynopsis(): string {
  return `${SYNOPSIS}\n`;
}

const SHARED_FLAGS = [
  "  [roots…]            limit the scan to the Projects under these directories",
  "  --harness <id>      scan this Harness only; repeatable",
  "                      claude-code, codex, cursor, gemini-cli, copilot, opencode",
  "  --no-git            never spawn git; git-tracked status stays unknown",
  "  --json              print the machine-readable document and nothing else",
  "  --pretty            indent the JSON; implies --json",
  "  --help, -h          print this page",
  "  --version, -V       print the version",
];

const GLOBAL = [
  "moldig — CleanMyMac for your AI setup.",
  "",
  "It scans, shows and cleans the Skills, MCP servers, Context files, Memory files and",
  "Harness cache that AI coding harnesses leave across every Project on a machine.",
  "",
  "Usage",
  "  moldig [roots…]          review one trusted cache-to-Trash Plan, then Clean",
  "  moldig scan [roots…]     read what every Harness left and print what is there",
  "  moldig audit [roots…]    open Inventory in a TTY; print Findings otherwise",
  "  moldig clean [roots…]    the same trusted Clean ritual, named explicitly",
  "  moldig purge [roots…]    explicitly Delete state for missing Projects in a TTY",
  "  moldig update [roots…]   Update recognised Skills, plugins and Docker MCP images",
  "",
  "Flags",
  ...SHARED_FLAGS,
  "  --no-read-signal    skip the memory read signal (audit, clean)",
  "  --fail-on <s>       audit: exit 1 on a Finding at this severity or above",
  "                      low (default), medium, high, never",
  "  --category <c>      audit, clean: restrict to this Category; repeatable",
  "  --severity <s>      audit: restrict to this severity and above",
  "  --older-than <days> clean: restrict to units older than this",
  "  --yes               clean: run unattended (a filter is required too)",
  "  --dry-run           clean: print the plan and stop",
  "",
  "Exit codes",
  "  0  the scan completed, or no Finding reached --fail-on",
  "  1  a Finding reached --fail-on, or an attempted action row failed",
  "  2  a usage or environment error, or clean refused to run",
  "",
  "The scan is read-only: it never runs a Harness, a sub-agent or an MCP server, and it",
  "never touches the network. `moldig --help <command>` prints a command's own page.",
];

const SCAN = [
  "moldig scan [roots…] — run the read-only scan and print what every Harness left.",
  "",
  "Prints one row per Harness with its presence and its counts, the Projects with what a",
  "session there loads, the totals and the Stray and Unreachable counts. With --json it",
  "prints the index document (schemaVersion 0) and nothing else.",
  "",
  "Flags",
  ...SHARED_FLAGS,
  "",
  "Exit codes: 0 the scan completed (Warnings do not change it) · 2 usage or environment error.",
];

const AUDIT = [
  "moldig audit [roots…] — scan, run the detectors and print the Findings.",
  "",
  "Prints the Headline number per Harness, the eight Categories with their counts and",
  "severity, then the Findings table. With --json it prints the index document plus",
  "findings[] and headline. --category and --severity restrict the table, the JSON",
  "findings[] and what --fail-on looks at.",
  "",
  "Flags",
  ...SHARED_FLAGS,
  "  --no-read-signal    skip the memory read signal; never-read facts stay unknown",
  "  --fail-on <s>       exit 1 on a Finding at this severity or above",
  "                      low (default), medium, high, never",
  "  --category <c>      duplicate, orphan, bloat, drift, shadow-memory,",
  "                      autogenerated, harness-cache, exposure; repeatable",
  "  --severity <s>      low, medium or high; keeps that severity and above",
  "",
  "Exit codes: 0 nothing at or above --fail-on · 1 something is · 2 usage or environment error.",
];

const CLEAN = [
  "moldig clean [roots…] — review one trusted cache-to-Trash Plan, then Clean.",
  "",
  "In a Project, the Plan contains only that Project's audit-preselected Harness cache. Outside",
  "a Project it contains the same safe cache across the scanned machine. The Plan is grouped by",
  "Harness and cache kind; expand only for paths, or use space to exclude a group or item. Enter",
  "is the confirmation. Memory files, Human-owned items, kept state, Live rows and non-Trash",
  "dispositions never enter this Plan.",
  "",
  "Unattended it needs both --yes and a filter (--category, --older-than or --harness), so a",
  "scheduled run can never remove more than it was told to.",
  "",
  "Flags",
  ...SHARED_FLAGS,
  "  --no-read-signal    skip the memory read signal",
  "  --category <c>      harness-cache (the only Category a v1 unattended clean reaches)",
  "  --older-than <days> keep only units older than this many days",
  "  --yes               run unattended; a filter is required with it",
  "  --dry-run           print the plan and stop; nothing is moved",
  "",
  "Every removal goes to the trash, or is preceded by a backup, and lands in a run manifest",
  "under moldig's data directory, whose path is printed with the summary.",
  "",
  "Exit codes: 0 every attempted row succeeded · 1 a row failed · 2 refused to run, or a",
  "usage or environment error.",
];

const PURGE = [
  "moldig purge [roots…] — explicitly Delete state for Projects whose directories are gone.",
  "",
  "Requires a terminal. Every missing Project starts selected as one human-scale Delete target;",
  "space excludes individual Projects and `a` selects all or none. The preview shows Project and",
  "Harness-record totals, then asks twice before anything runs. Files go to the OS trash and store",
  "entries are backed up before precise edits. Live state stays. Purge is the command name; the",
  "underlying Action remains Delete, never Clean.",
  "",
  "Flags",
  "  [roots…]            limit missing Projects to these directories",
  "  --no-git            never spawn git while rebuilding the Index",
  "  --help, -h          print this page",
  "  --version, -V       print the version",
  "",
  "Exit codes: 0 every attempted row succeeded · 1 a row failed · 2 no terminal, usage or",
  "environment error.",
];

const UPDATE = [
  "moldig update [roots…] — Update recognised Skills, plugins and Docker MCP images.",
  "",
  "Requires a terminal. Skills installed by the Vercel skills CLI are grouped by lock scope and",
  "updated once per scope; locally modified or differing copies stay for an individual decision.",
  "A plugin with one such Skill stays too. Plugin-owned MCP servers update with their parent plugin.",
  "Remote servers and ephemeral npx/uvx launchers have no separate local update step. A Docker MCP",
  "image is pulled once per trusted Docker command, context and platform target. Launcher version",
  "pins, Docker digests, direct binaries and unknown launchers stay with a reason.",
  "",
  "Flags",
  "  [roots…]            limit the machine-wide Update Plan to these directories",
  "  --no-git            never spawn git while rebuilding the Index",
  "  --help, -h          print this page",
  "  --version, -V       print the version",
  "",
  "Exit codes: 0 every updater run succeeded · 1 an updater run failed · 2 no terminal, usage or",
  "environment error.",
];

const PAGES: Record<CommandName, readonly string[]> = {
  default: GLOBAL,
  scan: SCAN,
  audit: AUDIT,
  clean: CLEAN,
  purge: PURGE,
  update: UPDATE,
};

export function helpPage(command: CommandName): string {
  return `${PAGES[command].join("\n")}\n`;
}
