/**
 * The human reports: the `scan` summary and the `audit` headline + Categories + Findings. Pure
 * string building — the index comes in, lines go out — so every layout is a snapshot test.
 *
 * Layout rules: nothing is wider than the width handed in (80 in a pipe), no cell ever wraps
 * (a cell too long is truncated with `…`), and with colour off the bytes are plain text.
 * The vocabulary is CONTEXT.md's, including the display order of the Categories (D85).
 */
import type { AuditIndex, Category, EntityKind, Finding, Harness, Index } from "@moldig/core";
import { CATEGORIES, type Severity } from "./args.js";
import {
  formatBytes,
  formatPercent,
  formatRange,
  formatTokens,
  plural,
  table,
  type Column,
} from "./format.js";
import type { Palette } from "./palette.js";

/** The glossary's name for every entity kind, in the order the scan summary lists them. */
const KIND_LABELS: readonly (readonly [EntityKind, string])[] = [
  ["context-file", "Context files"],
  ["skill", "Skills"],
  ["mcp-server", "MCP servers"],
  ["memory-file", "Memory files"],
  ["agent-definition", "Agent definitions"],
  ["plugin", "Plugins"],
  ["settings-file", "Settings files"],
  ["harness-cache", "Harness cache"],
];

/** The glossary spells two Categories with a space; the flag and the JSON keep the kebab id. */
const CATEGORY_LABELS: Readonly<Record<Category, string>> = {
  duplicate: "duplicate",
  orphan: "orphan",
  bloat: "bloat",
  drift: "drift",
  "shadow-memory": "shadow memory",
  autogenerated: "autogenerated",
  "harness-cache": "harness cache",
  exposure: "exposure",
};

export interface ReportStyle {
  palette: Palette;
  width: number;
}

function title(style: ReportStyle, text: string): string {
  return style.palette.bold(text);
}

function severityBadge(style: ReportStyle, severity: Severity): string {
  const { red, yellow, dim } = style.palette;
  if (severity === "high") return red("high");
  if (severity === "medium") return yellow("medium");
  return dim("low");
}

function harnessLabel(index: Index, harness: string | null): string {
  return index.harnesses.find((item) => item.harness === harness)?.displayName ?? "—";
}

/** `orphan` is how index v0 spells a Project whose directory is gone; the report says so. */
function reachabilityLabel(reachability: "present" | "orphan" | "unreachable"): string {
  return reachability === "orphan" ? "gone" : reachability;
}

function bytesOf(index: Index, project: string | null, kind: EntityKind): number {
  return index.entities
    .filter((entity) => entity.project === project && entity.kind === kind)
    .reduce((sum, entity) => sum + entity.metrics.bytes, 0);
}

// ---------- scan ----------

export function scanReport(index: Index, style: ReportStyle): string[] {
  const lines: string[] = [];
  const { dim } = style.palette;

  const harnessColumns: Column[] = [
    { header: "Harness", flex: true },
    { header: "Presence" },
    { header: "Version" },
    { header: "Projects", align: "right" },
    { header: "Warnings", align: "right" },
  ];
  const harnessRows = index.harnesses.map((harness) => {
    const projects = index.projects.filter(
      (project) => project.perHarness[harness.harness] !== undefined,
    ).length;
    const warnings = index.warnings.filter(
      (item) => item.harness === harness.harness || item.harness === null,
    ).length;
    return [
      harness.displayName,
      harness.presence,
      harness.version ?? dim("—"),
      projects.toString(),
      warnings.toString(),
    ];
  });
  lines.push(title(style, "Harnesses"), ...table(harnessColumns, harnessRows, style.width), "");

  const kindColumns: Column[] = [
    { header: "Kind", flex: true },
    ...index.harnesses.map((harness): Column => ({ header: harness.harness, align: "right" })),
  ];
  const countOf = (harness: string, kind: EntityKind): number =>
    index.entities.filter((entity) => entity.harness === harness && entity.kind === kind).length;
  const sumOf = (harness: string, pick: (kind: EntityKind) => boolean): number =>
    index.entities
      .filter((entity) => entity.harness === harness && pick(entity.kind))
      .reduce((sum, entity) => sum + entity.metrics.bytes, 0);
  const row = (label: string, cell: (harness: Harness) => string): string[] => {
    const cells = [label];
    for (const harness of index.harnesses) cells.push(cell(harness));
    return cells;
  };
  const kindRows = [
    ...KIND_LABELS.map(([kind, label]) =>
      row(label, (harness) => countOf(harness.harness, kind).toString()),
    ),
    row("Harness cache bytes", (harness) =>
      formatBytes(sumOf(harness.harness, (kind) => kind === "harness-cache")),
    ),
    row("Memory file bytes", (harness) =>
      formatBytes(sumOf(harness.harness, (kind) => kind === "memory-file")),
    ),
    row("All bytes", (harness) => formatBytes(sumOf(harness.harness, () => true))),
  ];
  lines.push(
    title(style, "What each Harness left"),
    ...table(kindColumns, kindRows, style.width),
    "",
  );

  const projectColumns: Column[] = [
    { header: "Project", flex: true },
    { header: "Reachability" },
    { header: "Harness" },
    { header: "Tokens/session", align: "right" },
    { header: "Harness cache", align: "right" },
  ];
  const projectRows = index.projects.flatMap((project) =>
    Object.entries(project.perHarness).map(([harness, facts]) => [
      project.displayName,
      reachabilityLabel(project.reachability),
      harnessLabel(index, harness),
      formatTokens(facts?.sessionLoad.tokens ?? 0),
      formatBytes(bytesOf(index, project.id, "harness-cache")),
    ]),
  );
  if (projectRows.length > 0) {
    lines.push(title(style, "Projects"), ...table(projectColumns, projectRows, style.width), "");
  }

  const present = index.projects.filter((project) => project.reachability === "present").length;
  const gone = index.projects.filter((project) => project.reachability === "orphan").length;
  const unreachable = index.projects.filter(
    (project) => project.reachability === "unreachable",
  ).length;
  const stray = index.breadcrumbs.filter((crumb) => crumb.project === null).length;
  lines.push(
    [
      `${plural(present, "Project")} present`,
      `${gone} gone`,
      `${unreachable} unreachable`,
      `${stray} Stray`,
    ].join(" · "),
    "",
  );

  const { totals } = index;
  lines.push(
    title(style, "Totals"),
    [
      plural(totals.entities, "entity", "entities"),
      plural(totals.files, "file"),
      formatBytes(totals.bytes),
    ].join(" · "),
    dim(
      [
        `harness cache ${formatBytes(totals.harnessCacheBytes)}`,
        `memory files ${formatBytes(totals.memoryBytes)}`,
        `${formatTokens(totals.tokens)} tokens on disk`,
      ].join(" · "),
    ),
  );
  return lines;
}

// ---------- audit ----------

const FOCUS_REASON: Readonly<Record<"cwd" | "most-expensive" | "none", string>> = {
  cwd: "the Project the working directory is in",
  "most-expensive": "the most expensive Project",
  none: "no Project",
};

function headlineLines(index: AuditIndex, style: ReportStyle): string[] {
  const { dim } = style.palette;
  const { headline } = index;
  const focused = index.projects.find((project) => project.id === headline.focus.project);
  const name = focused?.displayName ?? "this machine";
  const lines = [
    title(style, "Headline number"),
    dim(`${name} — ${FOCUS_REASON[headline.focus.reason]}`),
  ];
  const installed = headline.perHarness.filter((entry) =>
    index.harnesses.some(
      (harness) => harness.harness === entry.harness && harness.presence === "installed",
    ),
  );
  if (installed.length === 0) {
    lines.push("no Harness is installed on this machine");
    return lines;
  }
  for (const entry of installed) {
    const adds = focused === undefined ? "" : ` + ${name} adds ${formatTokens(entry.project.mid)}`;
    lines.push(
      harnessLabel(index, entry.harness),
      `  every session pays ${formatTokens(entry.baseline.mid)}${adds} = ${formatTokens(entry.total.mid)} tokens/session`,
    );
    const parts: string[] = [];
    if (entry.total.low !== entry.total.high) {
      parts.push(`${formatRange(entry.total.low, entry.total.high)} tokens`);
    }
    if (entry.pctOfContext !== null) {
      parts.push(`${formatPercent(entry.pctOfContext)} of the context window`);
    }
    if (parts.length > 0) lines.push(dim(`  ${parts.join(" · ")}`));
  }
  return lines;
}

function categoryLines(findings: readonly Finding[], style: ReportStyle): string[] {
  const columns: Column[] = [
    { header: "Category", flex: true },
    { header: "Findings", align: "right" },
    { header: "Severity" },
  ];
  const rows = CATEGORIES.map((category) => {
    const mine = findings.filter((finding) => finding.category === category);
    const worst = mine.some((finding) => finding.severity === "high")
      ? "high"
      : mine.some((finding) => finding.severity === "medium")
        ? "medium"
        : "low";
    return [
      CATEGORY_LABELS[category],
      mine.length.toString(),
      mine.length === 0 ? style.palette.dim("—") : severityBadge(style, worst),
    ];
  });
  return [title(style, "Categories"), ...table(columns, rows, style.width)];
}

function impactOf(finding: Finding): string {
  if (finding.impact.bytes === 0 && finding.impact.tokens !== null) {
    return `${formatTokens(finding.impact.tokens)} tokens`;
  }
  return formatBytes(finding.impact.bytes);
}

function findingLines(findings: readonly Finding[], style: ReportStyle): string[] {
  if (findings.length === 0) return [title(style, "Findings"), "nothing to look at"];
  const columns: Column[] = [
    { header: "Severity" },
    { header: "Category" },
    { header: "Finding", flex: true },
    { header: "Impact", align: "right" },
  ];
  const rows = findings.map((finding) => [
    severityBadge(style, finding.severity),
    CATEGORY_LABELS[finding.category],
    finding.message,
    impactOf(finding),
  ]);
  return [title(style, "Findings"), ...table(columns, rows, style.width)];
}

/**
 * D85's display order: the Categories in the glossary's order, then the pinned flags, then
 * `impact.bytes` descending. The serialised order of `findings[]` stays the engine's.
 */
const PINNED = ["shared", "sensitive", "secret-exposed", "memory", "live", "user-content"];

export function displayOrder(findings: readonly Finding[]): Finding[] {
  const pinnedRank = (finding: Finding): number => {
    const ranks = finding.flags.map((flag) => PINNED.indexOf(flag)).filter((rank) => rank !== -1);
    return ranks.length === 0 ? PINNED.length : Math.min(...ranks);
  };
  return findings.toSorted(
    (a, b) =>
      CATEGORIES.indexOf(a.category) - CATEGORIES.indexOf(b.category) ||
      pinnedRank(a) - pinnedRank(b) ||
      b.impact.bytes - a.impact.bytes ||
      a.id.localeCompare(b.id),
  );
}

export function auditReport(index: AuditIndex, style: ReportStyle): string[] {
  const findings = displayOrder(index.findings);
  return [
    ...headlineLines(index, style),
    "",
    ...categoryLines(findings, style),
    "",
    ...findingLines(findings, style),
    "",
    style.palette.dim(
      index.warnings.length === 0
        ? "no Warning"
        : `${plural(index.warnings.length, "Warning")} (on stderr)`,
    ),
  ];
}
