import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { loadFixture, normaliseSnapshot, type FixtureTree } from "@moldig/core/testing";
import { runCli, type Io } from "./run.js";
import type { OpenTui, TuiRequest } from "./tui/index.js";

/** Ticket 26's TUI behind its port: `runCli` only has to decide whether to open it. */
function fakeTui(seen: TuiRequest[]): OpenTui {
  return (request) => {
    seen.push(request);
    return Promise.resolve({ summary: "summary from the TUI\n", failedRows: 0 });
  };
}

/** The same clock the core snapshots use, so the fixture's `ages` land on the same day grid. */
const NOW = new Date("2026-08-26T12:00:00.000Z");
/** Pinned so one snapshot holds on macOS, Linux and Windows alike (D100). */
const PLATFORM = "darwin";
// oxlint-disable-next-line no-control-regex -- an escape sequence is exactly what is looked for
const ESCAPES = /\u001B\[/u;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

/** stdout parsed as a JSON object, with no assertion from `any`. */
function jsonOf(text: string): Record<string, unknown> {
  const parsed: unknown = JSON.parse(text);
  if (!isRecord(parsed)) throw new Error("expected a JSON object on stdout");
  return parsed;
}

function findingsOf(text: string): Record<string, unknown>[] {
  const findings: unknown = jsonOf(text)["findings"];
  if (!Array.isArray(findings)) throw new Error("expected findings[] on stdout");
  const items: unknown[] = findings;
  return items.filter(isRecord);
}

let tree: FixtureTree;

interface Run {
  code: number;
  out: string;
  err: string;
}

async function run(argv: readonly string[], overrides: Partial<Io> = {}): Promise<Run> {
  let out = "";
  let err = "";
  const io: Io = {
    stdout: (chunk) => {
      out += chunk;
    },
    stderr: (chunk) => {
      err += chunk;
    },
    isTTY: false,
    columns: 80,
    env: { NO_COLOR: "1" },
    cwd: tree.cwd,
    home: tree.home,
    platform: PLATFORM,
    now: NOW,
    ...overrides,
  };
  const code = await runCli(argv, io);
  return { code, out, err };
}

beforeAll(async () => {
  tree = await loadFixture("claude-code/breadcrumbs", {
    cwd: "root/project-a",
    now: NOW,
    platform: PLATFORM,
  });
});

afterAll(async () => {
  await tree.cleanup();
});

describe("moldig scan", () => {
  it("prints the Harness, a Project and the totals, and exits 0", async () => {
    const { code, out } = await run(["scan", "--no-git", tree.root]);
    expect(code).toBe(0);
    expect(out).toContain("Claude Code");
    expect(out).toContain("installed");
    expect(out).toContain("project-a");
    expect(out).toContain("Totals");
    expect(out).toContain("tokens on disk");
    expect(out).toContain("1 Project present · 1 gone · 0 unreachable");
  });

  it("prints index v0 with --json and nothing else on stdout", async () => {
    const { code, out } = await run(["scan", "--no-git", "--json", tree.root]);
    expect(code).toBe(0);
    expect(jsonOf(out)).toMatchObject({ schemaVersion: 0, scan: { platform: PLATFORM } });
    expect(out.trimEnd()).not.toContain("\n"); // compact: one line
    expect(out).not.toMatch(ESCAPES);
  });

  it("--pretty indents and implies --json", async () => {
    const { code, out } = await run(["scan", "--no-git", "--pretty", tree.root]);
    expect(code).toBe(0);
    expect(out).toContain('\n  "schemaVersion": 0,');
    expect(jsonOf(out)).toMatchObject({ schemaVersion: 0 });
  });

  it("matches the summary snapshot at 80 columns", async () => {
    const { out } = await run(["scan", "--no-git", tree.root]);
    await expect(normaliseSnapshot(out, tree)).toMatchFileSnapshot("./__snapshots__/scan.txt");
  });
});

describe("moldig audit", () => {
  it("prints the Headline number, the eight Categories and the Findings", async () => {
    const { code, out } = await run(["audit", "--no-git", tree.root]);
    expect(code).toBe(1); // Findings at or above the default --fail-on low
    expect(out).toContain("Headline number");
    expect(out).toContain("every session pays");
    expect(out).toContain("tokens/session");
    for (const category of [
      "duplicate",
      "orphan",
      "bloat",
      "drift",
      "shadow memory",
      "autogenerated",
      "harness cache",
      "exposure",
    ]) {
      expect(out).toContain(category);
    }
    expect(out).toContain("Findings");
  });

  it("matches the audit snapshot at 80 columns", async () => {
    const { out } = await run(["audit", "--no-git", tree.root]);
    await expect(normaliseSnapshot(out, tree)).toMatchFileSnapshot("./__snapshots__/audit.txt");
  });

  it("prints the AuditIndex with --json", async () => {
    const { code, out } = await run(["audit", "--no-git", "--json", tree.root]);
    expect(code).toBe(1);
    expect(jsonOf(out)).toMatchObject({
      schemaVersion: 0,
      headline: { scope: "user-controllable" },
    });
    expect(findingsOf(out).length).toBeGreaterThan(0);
  });

  it("--fail-on decides the exit code", async () => {
    const [low, medium, high, never] = await Promise.all([
      run(["audit", "--no-git", tree.root]),
      run(["audit", "--no-git", "--fail-on", "medium", tree.root]),
      run(["audit", "--no-git", "--fail-on", "high", tree.root]),
      run(["audit", "--no-git", "--fail-on", "never", tree.root]),
    ]);
    expect([low?.code, medium?.code, high?.code, never?.code]).toEqual([1, 1, 0, 0]);
  });

  it("--category and --severity filter the table, findings[] and --fail-on (D15)", async () => {
    const only = await run(["audit", "--no-git", "--category", "orphan", "--json", tree.root]);
    expect(findingsOf(only.out).map((finding) => finding["category"])).toEqual(["orphan"]);
    expect(jsonOf(only.out)["headline"]).not.toBeUndefined(); // the headline is never filtered
    expect(only.code).toBe(1);

    const high = await run(["audit", "--no-git", "--severity", "high", "--json", tree.root]);
    expect(findingsOf(high.out)).toEqual([]);
    expect(high.code).toBe(0);

    const table = await run(["audit", "--no-git", "--category", "orphan", tree.root]);
    expect(table.out).toContain("orphan");
    expect(table.out).not.toContain("kept under Claude Code's user scope");
  });

  it("--no-read-signal adds the read-signal-skipped Warning on stderr", async () => {
    const { err } = await run(["audit", "--no-git", "--no-read-signal", tree.root]);
    expect(err).toContain("warning read-signal-skipped: memory read signal not computed");
  });
});

describe("moldig without a command", () => {
  it("prints the audit table and the shareable summary in a pipe, and exits 0 (D5, D132)", async () => {
    const { code, out } = await run(["--no-git", tree.root]);
    expect(code).toBe(0);
    expect(out).toContain("Headline number");
    expect(out).toContain("moldig — project-a (cwd)");
    expect(out).toContain("Nothing moved (preview):");
    expect(out).toContain("Clean: 3 rows");
    expect(out).not.toContain("ticket 26");
  });

  it("opens the TUI on the scan screen in a terminal and prints the summary it hands back", async () => {
    const seen: TuiRequest[] = [];
    const { code, out } = await run(["--no-git", tree.root], {
      isTTY: true,
      stdinIsTTY: true,
      openTui: fakeTui(seen),
    });
    expect(code).toBe(0);
    expect(seen).toHaveLength(1);
    expect(seen[0]?.initialRoute).toBeUndefined(); // the TUI's own default: the Scan screen
    expect(seen[0]?.index.headline.focus.reason).toBe("cwd");
    expect(out).toBe("\nsummary from the TUI\n");
  });

  it("stays on the printed path without a terminal on stdin", async () => {
    const seen: TuiRequest[] = [];
    const { out } = await run(["--no-git", tree.root], { isTTY: true, openTui: fakeTui(seen) });
    expect(seen).toHaveLength(0);
    expect(out).toContain("Headline number");
  });

  it("--json never opens the TUI (D14)", async () => {
    const seen: TuiRequest[] = [];
    const { code, out } = await run(["--no-git", "--json", tree.root], {
      isTTY: true,
      stdinIsTTY: true,
      openTui: fakeTui(seen),
    });
    expect(code).toBe(0);
    expect(seen).toHaveLength(0);
    expect(jsonOf(out)).toMatchObject({ headline: { scope: "user-controllable" } });
  });

  it("a failed row in the TUI's run exits 1 (D17)", async () => {
    const { code } = await run(["--no-git", tree.root], {
      isTTY: true,
      stdinIsTTY: true,
      openTui: () => Promise.resolve({ summary: "s\n", failedRows: 2 }),
    });
    expect(code).toBe(1);
  });

  it("--json is audit --json (D14)", async () => {
    const { code, out } = await run(["--no-git", "--json", tree.root]);
    expect(code).toBe(0);
    expect(findingsOf(out).length).toBeGreaterThan(0);
    expect(jsonOf(out)).toMatchObject({ headline: { scope: "user-controllable" } });
  });
});

describe("moldig clean", () => {
  it("refuses without a terminal and without --yes, and says so (D124)", async () => {
    const { code, out, err } = await run(["clean", tree.root]);
    expect(code).toBe(2);
    expect(out).toBe("");
    expect(err).toContain("no terminal to confirm in");
    expect(err).toContain("--yes and a filter");
  });

  it("refuses --yes without a filter (D124)", async () => {
    const { code, err } = await run(["clean", "--yes", tree.root]);
    expect(code).toBe(2);
    expect(err).toContain("--yes needs a filter as well");
  });

  it("refuses a Category an unattended clean cannot reach (D16)", async () => {
    const { code, err } = await run(["clean", "--yes", "--category", "bloat", tree.root]);
    expect(code).toBe(2);
    expect(err).toContain("harness-cache only");
  });

  it("says --dry-run is not implemented instead of faking a plan", async () => {
    const { code, out } = await run(["clean", "--dry-run", tree.root]);
    expect(code).toBe(0);
    expect(out).toContain("not implemented until the actions engine lands (ticket 24)");
  });

  it("opens the TUI on the selection panel in a terminal (D4)", async () => {
    const seen: TuiRequest[] = [];
    const { code, out } = await run(["clean", tree.root], {
      isTTY: true,
      stdinIsTTY: true,
      openTui: fakeTui(seen),
    });
    expect(code).toBe(0);
    expect(seen[0]?.initialRoute).toEqual({ screen: "selection" });
    expect(out).toBe("\nsummary from the TUI\n");
  });

  it("says so instead of opening the panel when there is no terminal", async () => {
    const { code, out } = await run(["clean", tree.root], { isTTY: true });
    expect(code).toBe(0);
    expect(out).toContain("no terminal to open the selection panel in");
    expect(out).toContain("nothing was removed");
  });

  it("does not pretend to sweep with --yes and a filter", async () => {
    const { code, out } = await run(["clean", "--yes", "--category", "harness-cache", tree.root]);
    expect(code).toBe(0);
    expect(out).toContain("nothing was removed");
  });
});

describe("usage errors exit 2", () => {
  it("an unknown flag", async () => {
    const { code, out, err } = await run(["scan", "--nope"]);
    expect(code).toBe(2);
    expect(out).toBe("");
    expect(err).toContain("moldig: unknown flag --nope");
    expect(err).toContain("usage: moldig");
  });

  it("an unknown Harness id, listing the valid ones", async () => {
    const { code, err } = await run(["scan", "--harness", "windsurf"]);
    expect(code).toBe(2);
    expect(err).toContain("claude-code, codex, cursor, gemini-cli, copilot, opencode");
  });

  it("an unknown Category and a bad severity", async () => {
    const bad = await Promise.all([
      run(["audit", "--category", "clutter"]),
      run(["audit", "--severity", "critical"]),
      run(["audit", "--fail-on", "always"]),
    ]);
    for (const { code } of bad) expect(code).toBe(2);
  });

  it("a Root that is not an existing directory (D23)", async () => {
    const missing = await run(["scan", `${tree.dir}/nowhere`]);
    expect(missing.code).toBe(2);
    expect(missing.err).toContain("no such directory");

    const file = await run(["scan", tree.path("home/.claude.json")]);
    expect(file.code).toBe(2);
    expect(file.err).toContain("not a directory");
  });

  it("a flag the command does not take", async () => {
    const { code, err } = await run(["scan", "--fail-on", "high"]);
    expect(code).toBe(2);
    expect(err).toContain("--fail-on is not a flag of scan");
  });

  it("an unsupported platform (D125)", async () => {
    const { code, err } = await run(["scan"], { platform: "freebsd" });
    expect(code).toBe(2);
    expect(err).toContain("moldig runs on darwin, linux, win32, not on freebsd");
  });
});

describe("--help and --version (D13)", () => {
  it("prints the global page", async () => {
    const { code, out } = await run(["--help"]);
    expect(code).toBe(0);
    expect(out).toContain("moldig — CleanMyMac for your AI setup.");
    expect(out).toContain("moldig scan [roots…]");
    expect(out).toContain("Exit codes");
  });

  it("prints a page per command", async () => {
    const commands = ["scan", "audit", "clean"];
    const pages = await Promise.all(commands.map((command) => run([command, "--help"])));
    for (const [i, page] of pages.entries()) {
      expect(page.code).toBe(0);
      expect(page.out.startsWith(`moldig ${commands[i]} [roots…]`)).toBe(true);
    }
  });

  it("prints the version", async () => {
    const { code, out } = await run(["--version"]);
    expect(code).toBe(0);
    expect(out.trim()).toMatch(/^\d+\.\d+\.\d+/u);
  });
});

describe("the output contract", () => {
  it("sends every Warning to stderr and none to stdout", async () => {
    const { out, err } = await run(["scan", "--no-git", tree.root]);
    expect(err).toContain("warning git-missing: git not run (git: false)");
    expect(err).toContain("warning: scanning only: Claude Code");
    expect(out.split("\n").some((line) => line.startsWith("warning"))).toBe(false);
  });

  it("folds a multi-line Warning message onto one line", async () => {
    // git fails on the fixture's HEAD-only repository and quotes the command it ran, newline
    // and all; the contract is one line per Warning.
    const { err } = await run(["scan", tree.root]);
    const lines = err.split("\n").filter((line) => line !== "");
    expect(lines.length).toBeGreaterThan(0);
    expect(lines.every((line) => line.startsWith("warning"))).toBe(true);
  });

  it("keeps stdout free of Warnings with --json too", async () => {
    const { out, err } = await run(["scan", "--no-git", "--json", tree.root]);
    expect(err).toContain("warning git-missing");
    expect(out.startsWith("{")).toBe(true);
  });

  it("writes no escape sequence when NO_COLOR is set, terminal or not", async () => {
    const runs = await Promise.all(
      [true, false].map((isTTY) =>
        run(["audit", "--no-git", tree.root], { isTTY, env: { NO_COLOR: "1" } }),
      ),
    );
    for (const { out } of runs) expect(out).not.toMatch(ESCAPES);
  });

  it("writes no escape sequence when TERM is dumb", async () => {
    const { out } = await run(["audit", "--no-git", tree.root], {
      isTTY: true,
      env: { TERM: "dumb" },
    });
    expect(out).not.toMatch(ESCAPES);
  });

  it("colours the report for FORCE_COLOR even in a pipe (D20)", async () => {
    const { out } = await run(["audit", "--no-git", tree.root], { env: { FORCE_COLOR: "1" } });
    expect(out).toMatch(ESCAPES);
  });

  it("never wraps a line past the width it was given", async () => {
    const widths = [80, 100];
    const runs = await Promise.all(
      widths.map((columns) => run(["audit", "--no-git", tree.root], { columns })),
    );
    for (const [i, { out }] of runs.entries()) {
      for (const line of out.split("\n")) expect(line.length).toBeLessThanOrEqual(widths[i] ?? 80);
    }
  });
});
