#!/usr/bin/env node
/**
 * Generates `moldig.rb` for the tap `guillermolg00/homebrew-tap` from a version already
 * published on npm. The formula is generated, never hand-edited: everything that changes
 * between releases is the `url` and the `sha256`, and both come from the registry.
 *
 *   node packaging/homebrew/generate-formula.mjs 0.1.0
 *   node packaging/homebrew/generate-formula.mjs 0.1.0 --out ~/Work/homebrew-tap/Formula
 *
 * It reads the registry, downloads the tarball to a temp directory, verifies it against the
 * sha512 the registry published, computes the sha256 Homebrew wants (the registry offers only
 * sha1 and sha512), renders the formula and prints the path it wrote. It never runs `brew`,
 * never pushes anything and needs no credentials. Dependency-free: `fetch`, `node:crypto`,
 * `node:fs/promises`, `node:os`, `node:path`.
 */
import { createHash } from "node:crypto";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE = "moldig";
const REGISTRY = "https://registry.npmjs.org";
const TAP = "guillermolg00/homebrew-tap";
const USAGE = `usage: node packaging/homebrew/generate-formula.mjs <version> [--out <dir-or-file>]

  <version>        a version already published on npm, e.g. 0.1.0
  --out <path>     where to write moldig.rb; a directory or a file path
                   (default: next to this script)

Prints the path it wrote. Copy it to <tap>/Formula/moldig.rb — see the README here.`;

/** `{ version, out }`, or a message explaining what is wrong with the arguments. */
function parseArgs(argv) {
  let version = null;
  let out = null;
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--help" || arg === "-h") return { help: true };
    if (arg === "--out") {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith("-")) return { error: "--out needs a path" };
      out = value;
      i += 1;
      continue;
    }
    if (arg.startsWith("--out=")) {
      out = arg.slice("--out=".length);
      continue;
    }
    if (arg.startsWith("-")) return { error: `unknown flag ${arg}` };
    if (version !== null) return { error: `unexpected argument ${arg}` };
    version = arg;
  }
  if (version === null) return { error: "a version is required" };
  // Semver enough to keep a typo out of a URL; the registry is the real authority.
  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(version)) {
    return { error: `"${version}" does not look like a published version` };
  }
  return { version, out };
}

async function fetchJson(url) {
  const response = await fetch(url, { headers: { accept: "application/json" } });
  if (!response.ok) {
    throw new Error(`${url} answered ${response.status} ${response.statusText}`);
  }
  return response.json();
}

async function fetchBytes(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`${url} answered ${response.status} ${response.statusText}`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

function digest(algorithm, bytes, encoding) {
  return createHash(algorithm).update(bytes).digest(encoding);
}

/**
 * The registry publishes `dist.integrity` as `sha512-<base64>`. Checking it before hashing the
 * bytes ourselves is what makes the sha256 in the formula trustworthy: a truncated or swapped
 * download would otherwise be baked into the tap.
 */
function verifyIntegrity(bytes, integrity) {
  if (typeof integrity !== "string" || !integrity.startsWith("sha512-")) {
    throw new Error(`the registry published no sha512 integrity for this version (${integrity})`);
  }
  const expected = integrity.slice("sha512-".length);
  const actual = digest("sha512", bytes, "base64");
  if (actual !== expected) {
    throw new Error(
      `the downloaded tarball does not match the registry's sha512.\n` +
        `  expected sha512-${expected}\n  got      sha512-${actual}`,
    );
  }
}

function formula({ version, url, sha256 }) {
  return `# Generated by packaging/homebrew/generate-formula.mjs — do not edit by hand.
# moldig ${version}
class Moldig < Formula
  desc "Scan, review and clean what AI coding harnesses leave across your projects"
  homepage "https://github.com/guillermolg00/moldig"
  url "${url}"
  sha256 "${sha256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/moldig --version")

    # Homebrew runs tests with HOME=testpath: an empty home yields an empty index v0.
    # \`scan --json\` is compact by default, hence the space-less match.
    output = shell_output("#{bin}/moldig scan --json")
    assert_match "\\"schemaVersion\\":0", output
  end
end
`;
}

async function main(argv) {
  const parsed = parseArgs(argv);
  if (parsed.help === true) {
    process.stdout.write(`${USAGE}\n`);
    return 0;
  }
  if (parsed.error !== undefined) {
    process.stderr.write(`generate-formula: ${parsed.error}\n\n${USAGE}\n`);
    return 2;
  }
  const { version, out } = parsed;

  process.stderr.write(`reading ${REGISTRY}/${PACKAGE}/${version}\n`);
  const manifest = await fetchJson(`${REGISTRY}/${PACKAGE}/${version}`);
  const url = manifest?.dist?.tarball;
  if (typeof url !== "string") {
    throw new Error(`the registry gave no tarball URL for ${PACKAGE}@${version}`);
  }

  process.stderr.write(`downloading ${url}\n`);
  const bytes = await fetchBytes(url);
  const dir = await mkdtemp(join(tmpdir(), "moldig-formula-"));
  const tarball = join(dir, `${PACKAGE}-${version}.tgz`);
  await writeFile(tarball, bytes);
  process.stderr.write(`  ${bytes.length} bytes → ${tarball}\n`);

  verifyIntegrity(bytes, manifest.dist.integrity);
  const sha256 = digest("sha256", bytes, "hex");
  process.stderr.write(`  sha512 matches the registry · sha256 ${sha256}\n`);

  const base = out === null ? dirname(fileURLToPath(import.meta.url)) : resolve(out);
  const target = base.endsWith(".rb") ? base : join(base, "moldig.rb");
  await writeFile(target, formula({ version, url, sha256 }));

  process.stderr.write(`\nCopy it into the tap ${TAP}:\n  cp ${target} <tap>/Formula/moldig.rb\n`);
  process.stdout.write(`${target}\n`);
  return 0;
}

const code = await main(process.argv.slice(2)).catch((error) => {
  process.stderr.write(`generate-formula: ${error instanceof Error ? error.message : error}\n`);
  return 1;
});
process.exitCode = code;
