// THROWAWAY PROTOTYPE (ticket 09) — smoke tests over the fake index with ink-testing-library.
// A `.test.ts` (no JSX) because the Vitest include pattern is `*.test.ts`.
import { render } from "ink-testing-library";
import { createElement as h } from "react";
import { describe, expect, it } from "vitest";
import { App, type AppProps } from "./App.js";
import { HOME, ROOT, fakeIndex } from "./data/fake-index.js";
import { type ActionKind, groupSelection } from "./lib/selection.js";

const base: AppProps = {
  index: fakeIndex,
  env: {},
  platform: "darwin",
  hostname: "test-host",
  interactive: true,
  linksSupported: false,
};

const settle = (): Promise<void> => new Promise((resolve) => setTimeout(resolve, 80));

const SESSION_2 = `harness-cache:${HOME}/.claude/projects/__ROOT__-vlue/22222222-0000-4000-8000-000000000002.jsonl`;
const SESSION_1 = `harness-cache:${HOME}/.claude/projects/__ROOT__-vlue/11111111-0000-4000-8000-000000000001.jsonl`;
const SKILL_DEPLOY = `skill:${ROOT}/vlue/.claude/skills/deploy`;
const SKILL_COPY = `skill:${ROOT}/travia/.claude/skills/agent-browser`;
const TRAVIA_CLAUDE_MD = `context-file:${ROOT}/travia/claude.md`;

describe("overview", () => {
  it("renders the headline and the eight categories from the fake index", () => {
    const { lastFrame, unmount } = render(
      h(App, { ...base, initialRoute: { screen: "overview" } }),
    );
    const frame = lastFrame() ?? "";
    expect(frame).toContain("Headline — vlue");
    expect(frame).toContain("Claude Code");
    expect(frame).toContain("Codex");
    expect(frame).toContain("every session pays");
    expect(frame).toContain("tokens/session");
    for (const category of [
      "duplicate",
      "orphan",
      "bloat",
      "drift",
      "shadow memory",
      "autogenerated",
      "harness cache",
      "exposure",
    ]) {
      expect(frame).toContain(category);
    }
    unmount();
  });
});

describe("items", () => {
  it("toggles a checkbox with space", async () => {
    const { lastFrame, stdin, unmount } = render(
      h(App, {
        ...base,
        initialRoute: {
          screen: "items",
          container: `project:${ROOT}/vlue`,
          title: "t",
          onlyIds: [SESSION_2],
        },
        initialMarks: new Map<string, ActionKind>(),
      }),
    );
    await settle();
    expect(lastFrame()).toContain("[ ]");
    expect(lastFrame()).not.toContain("[x]");
    stdin.write("j"); // from the cache group row to its unit
    await settle();
    stdin.write(" ");
    await settle();
    expect(lastFrame()).toContain("[x]");
    stdin.write(" ");
    await settle();
    expect(lastFrame()).not.toContain("[x]");
    unmount();
  });
});

describe("selection panel", () => {
  const marks = new Map<string, ActionKind>([
    [TRAVIA_CLAUDE_MD, "open"],
    [SKILL_COPY, "update"],
    [SKILL_DEPLOY, "delete"],
    [SESSION_1, "clean"],
  ]);

  it("groups by action in the order Clean / Delete / Update / Open", () => {
    const groups = groupSelection(fakeIndex, marks);
    expect(groups.map((g) => g.title)).toEqual(["Clean", "Delete", "Update", "Open"]);
    expect(groups[0]?.rows[0]?.disposition.text).toBe("→ Trash");
    expect(groups[2]?.rows[0]?.disposition.text).toBe("→ backup + npx skills update agent-browser");
  });

  it("renders the groups with their counts", () => {
    const { lastFrame, unmount } = render(
      h(App, { ...base, initialRoute: { screen: "selection" }, initialMarks: marks }),
    );
    const frame = lastFrame() ?? "";
    const positions = ["Clean (1)", "Delete (1)", "Update (1)", "Open (1)"].map((label) =>
      frame.indexOf(label),
    );
    expect(positions.every((p) => p >= 0)).toBe(true);
    expect(positions.toSorted((a, b) => a - b)).toEqual(positions);
    expect(frame).toContain("→ Trash");
    expect(frame).toContain("shared row");
    unmount();
  });
});
