/**
 * `audit`: the judgement pass over a finished `scan` [ADR-0007]. It computes the one signal the
 * scan never computes — the memory read signal, Claude Code only in v1 — runs the eight detectors
 * of §7 and the headline, and returns an `AuditIndex`. Nothing here writes to disk, spawns a
 * harness or opens a credentials store [ADR-0001].
 *
 * The eight categories live one per file: duplicate, orphan, bloat, drift, shadow-memory,
 * autogenerated, harness-cache and exposure — the glossary's order, which is also the display
 * order of `./order.js`. `findings[]` itself is serialised in the deterministic order of 07's
 * Answer, so two audits of one machine produce identical JSON.
 *
 * `readSignal: false` (`--no-read-signal`) skips the signal pass and appends one warning; memory
 * files then stay `not-computed` and no never-read verdict is claimed [D107].
 */
import type { AuditIndex, Finding, Index } from "../index/types.js";
import { claudeOrphanFindings } from "../adapters/claude-code/orphans.js";
import { withReadSignal } from "../adapters/claude-code/read-signal.js";
import { warning } from "../scan/context.js";
import { autogeneratedFindings } from "./autogenerated.js";
import { bloatFindings } from "./bloat.js";
import { driftFindings } from "./drift.js";
import { duplicateFindings } from "./duplicate.js";
import { exposureFindings } from "./exposure.js";
import { harnessCacheFindings } from "./harness-cache.js";
import { headlineOf } from "./headline.js";
import { compareSerialised } from "./order.js";
import { orphanFindings } from "./orphan.js";
import { shadowMemoryFindings } from "./shadow-memory.js";

export interface AuditOptions {
  /** Project id to focus; default per §7.10: the Project enclosing cwd, else the most expensive. */
  focus?: string;
  /** Default `true`; `false` (`--no-read-signal`) leaves memory files `not-computed` and warns. */
  readSignal?: boolean;
}

/** The two orders of §7.1: the CLI and the TUI share `compareForDisplay` rather than each
 * keeping a category table of their own [D85]. */
export { CATEGORY_ORDER, compareForDisplay, compareSerialised, PINNED_FLAGS } from "./order.js";
/** Ticket 08's predicates, re-exported where the engine's consumers already look for them. */
export { isCleanable, isPreselected } from "./harness-cache.js";

export async function audit(scanned: Index, options: AuditOptions = {}): Promise<AuditIndex> {
  const index: Index =
    options.readSignal === false
      ? {
          ...scanned,
          warnings: [
            ...scanned.warnings,
            warning(
              "read-signal-skipped",
              "memory read signal not computed: never-read facts are unknown",
              null,
              null,
              "skipped",
            ),
          ],
        }
      : await withReadSignal(scanned);
  const findings: Finding[] = [
    ...duplicateFindings(index),
    ...orphanFindings(index),
    // The Claude adapter's own Orphan rows (D48, D53): registry, lock and settings entries that
    // name something gone have no entity for a general detector to see.
    ...(await claudeOrphanFindings(index)),
    ...bloatFindings(index),
    ...driftFindings(index),
    ...shadowMemoryFindings(index),
    ...(await autogeneratedFindings(index)),
    ...harnessCacheFindings(index),
    ...(await exposureFindings(index)),
  ].toSorted(compareSerialised);
  return { ...index, findings, headline: headlineOf(index, options.focus) };
}
