/**
 * `audit`: the memory read signal (ticket 07/08: computed here and in interactive `clean`,
 * never in `scan`; `readSignal: false` skips it with a `read-signal-skipped` warning), then
 * the detectors that run over a scan (ADR-0007: findings live outside the index) and the
 * headline. Categories implemented here: orphan (a Project whose directory is gone),
 * harness-cache (one finding per container × cacheKind with per-unit preselect, ticket 08),
 * shadow-memory (memory units kept under the harness's user scope, away from the Project they
 * describe) and duplicate (same content, same endpoint). bloat, autogenerated, drift and
 * exposure are not specified yet.
 */
import type {
  AuditIndex,
  Entity,
  Finding,
  Flag,
  HarnessCache,
  Headline,
  Index,
  MemoryFile,
  TokenRange,
} from "../index/types.js";
import { withReadSignal } from "../adapters/claude-code/read-signal.js";
import { warning } from "../scan/context.js";
import { addRanges, applyMultiplier, multiplierFor } from "../tokens/tokenizer.js";

export interface AuditOptions {
  /** Project id to focus; default per ticket 07: the Project enclosing cwd, else the most expensive. */
  focus?: string;
  /** Default `true`; `false` (`--no-read-signal`) leaves memory files `not-computed` and warns. */
  readSignal?: boolean;
}

const MEDIUM_BYTES = 100 * 1024 * 1024;
const MEDIUM_UNITS = 50;

function byCategoryThenTarget(a: Finding, b: Finding): number {
  const ta = a.targets[0]?.id ?? "";
  const tb = b.targets[0]?.id ?? "";
  return (
    a.category.localeCompare(b.category) ||
    (ta < tb ? -1 : ta > tb ? 1 : 0) ||
    a.id.localeCompare(b.id)
  );
}

function plural(count: number, noun: string, pluralNoun = `${noun}s`): string {
  return `${count} ${count === 1 ? noun : pluralNoun}`;
}

function sizeOf(bytes: number): string {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${bytes} B`;
}

function displayNameOf(index: Index, projectId: string | null): string {
  if (projectId === null) return "the user scope";
  return index.projects.find((project) => project.id === projectId)?.displayName ?? projectId;
}

function harnessNameOf(index: Index, harnessId: string | null): string {
  return (
    index.harnesses.find((harness) => harness.harness === harnessId)?.displayName ?? "the harness"
  );
}

/** Ticket 08: swept ∧ retention.days ∧ ageDays > days ∧ liveGuard.alive === false ∧ ¬userContent. */
export function isPreselected(unit: HarnessCache): boolean {
  return (
    unit.rule === "swept" &&
    unit.retention.days !== null &&
    unit.metrics.ageDays !== null &&
    unit.metrics.ageDays > unit.retention.days &&
    unit.liveGuard !== null &&
    !unit.liveGuard.alive &&
    !unit.userContent
  );
}

function orphanFindings(index: Index): Finding[] {
  const out: Finding[] = [];
  for (const project of index.projects) {
    if (project.reachability !== "orphan") continue;
    const crumbs = index.breadcrumbs.filter((crumb) => crumb.project === project.id);
    const state = index.entities.filter(
      (entity) =>
        entity.project === project.id &&
        entity.ownership === "harness" &&
        entity.protection === "none",
    );
    const targets: Finding["targets"] = [
      ...crumbs.map((crumb) => ({ id: crumb.id, role: "breadcrumb" as const })),
      ...state.map((entity) => ({ id: entity.id, role: "state" as const, preselect: false })),
    ];
    const evidence: Finding["evidence"] = [{ kind: "path-missing", detail: project.path }];
    for (const crumb of crumbs) {
      const lastSessionId = crumb.refs.lastSessionId;
      if (lastSessionId === undefined) continue;
      const known = index.entities.some(
        (entity) => entity.kind === "harness-cache" && entity.session === lastSessionId,
      );
      if (!known)
        evidence.push({
          kind: "breadcrumb-ref",
          detail: `lastSessionId ${lastSessionId} names a transcript that exists in no slug directory`,
        });
    }
    const memory = state.filter((entity) => entity.kind === "memory-file");
    const cache = state.filter((entity) => entity.kind === "harness-cache");
    const parts: string[] = [plural(crumbs.length, "breadcrumb")];
    if (memory.length > 0) parts.push(plural(memory.length, "memory file"));
    if (cache.length > 0) parts.push(plural(cache.length, "harness cache unit"));
    const harnesses = [...new Set(crumbs.map((crumb) => crumb.harness))].map((id) =>
      harnessNameOf(index, id),
    );
    const flags: Flag[] = [];
    if (memory.length > 0) flags.push("memory");
    if (state.some((entity) => entity.sensitive)) flags.push("sensitive");
    out.push({
      id: `finding:orphan:${project.id}`,
      category: "orphan",
      severity: "medium",
      container: project.id,
      targets,
      message: `${project.displayName}: directory gone; ${parts.join(", ")} left behind by ${harnesses.join(", ") || "a harness"}`,
      evidence,
      confidence: "certain",
      impact: {
        bytes: state.reduce((sum, entity) => sum + entity.metrics.bytes, 0),
        tokens:
          memory.length > 0
            ? memory.reduce((sum, entity) => sum + (entity.metrics.tokens?.o200k ?? 0), 0)
            : null,
        files: state.reduce((sum, entity) => sum + (entity.metrics.files ?? 0), 0),
      },
      flags,
      action: { kind: state.length > 0 ? "clean" : "none", preselect: false, locator: null },
    });
  }
  return out;
}

function harnessCacheFindings(index: Index): Finding[] {
  const groups = new Map<string, { container: string; cacheKind: string; units: HarnessCache[] }>();
  for (const entity of index.entities) {
    if (entity.kind !== "harness-cache" || entity.protection !== "none") continue;
    if (entity.rule !== "swept" && entity.rule !== "undocumented") continue;
    const container = entity.project ?? `harness:${entity.harness ?? "unknown"}`;
    const key = `${container} ${entity.cacheKind}`;
    const group = groups.get(key) ?? { container, cacheKind: entity.cacheKind, units: [] };
    group.units.push(entity);
    groups.set(key, group);
  }
  const out: Finding[] = [];
  for (const [, { container, cacheKind, units }] of groups) {
    const sorted = units.toSorted((a, b) => a.id.localeCompare(b.id));
    const bytes = sorted.reduce((sum, unit) => sum + unit.metrics.bytes, 0);
    const files = sorted.reduce((sum, unit) => sum + (unit.metrics.files ?? 0), 0);
    const preselected = sorted.filter((unit) => isPreselected(unit));
    const harnessName = harnessNameOf(index, sorted[0]?.harness ?? null);
    const retention = sorted[0]?.retention ?? {
      days: null,
      bytes: null,
      count: null,
      source: null,
    };
    const noun = cacheKind === "transcript" ? "session" : cacheKind.replaceAll("-", " ");
    let message: string;
    if (retention.days !== null) {
      message =
        preselected.length > 0
          ? `${plural(preselected.length, noun)} older than the ${retention.days}-day retention ${harnessName} sweeps itself (${plural(sorted.length, noun)}, ${sizeOf(bytes)})`
          : `${plural(sorted.length, noun)} (${sizeOf(bytes)}) within the ${retention.days}-day retention ${harnessName} sweeps itself`;
    } else if (retention.count !== null) {
      message = `${plural(sorted.length, noun)} (${sizeOf(bytes)}); ${harnessName} keeps the ${retention.count} newest`;
    } else {
      message = `${plural(sorted.length, noun)} (${sizeOf(bytes)}) ${harnessName} documents no sweep for`;
    }
    const flags: Flag[] = [];
    if (sorted.some((unit) => unit.sensitive)) flags.push("sensitive");
    if (sorted.some((unit) => unit.userContent)) flags.push("user-content");
    if (sorted.some((unit) => unit.liveGuard?.alive === true)) flags.push("live");
    const evidence: Finding["evidence"] = [];
    if (retention.days !== null) {
      const oldest = sorted.reduce<number | null>(
        (max, unit) =>
          unit.metrics.ageDays === null ? max : Math.max(max ?? 0, unit.metrics.ageDays),
        null,
      );
      evidence.push({
        kind: "retention-rule",
        detail: `${retention.source ?? "retention"} = ${retention.days}; oldest unit ${oldest ?? 0} days old`,
      });
    } else if (retention.count !== null) {
      evidence.push({
        kind: "retention-rule",
        detail: `${retention.source ?? "retention"} keeps ${retention.count}`,
      });
    } else {
      evidence.push({ kind: "retention-rule", detail: "no documented sweep" });
    }
    out.push({
      id: `finding:harness-cache:${container}:${cacheKind}`,
      category: "harness-cache",
      severity: bytes > MEDIUM_BYTES || sorted.length > MEDIUM_UNITS ? "medium" : "low",
      container,
      targets: sorted.map((unit) => ({
        id: unit.id,
        role: "subject" as const,
        preselect: isPreselected(unit),
      })),
      message,
      evidence,
      confidence: "certain",
      impact: { bytes, tokens: null, files },
      flags,
      action: { kind: "clean", preselect: preselected.length > 0, locator: null },
    });
  }
  return out;
}

function shadowMemoryFindings(index: Index): Finding[] {
  const units = new Map<string, MemoryFile[]>();
  for (const entity of index.entities) {
    if (entity.kind !== "memory-file" || entity.scope !== "user") continue;
    if (entity.owner.startsWith("agent:")) continue;
    // Shadow memory describes a Project (CONTEXT.md); a stray unit (the home directory's
    // memory) describes none: it is listed under the user scope, not filed here.
    if (entity.project === null) continue;
    units.set(entity.unit, [...(units.get(entity.unit) ?? []), entity]);
  }
  const out: Finding[] = [];
  for (const [unit, files] of units) {
    const sorted = files.toSorted((a, b) =>
      a.role === "index" ? -1 : b.role === "index" ? 1 : a.id.localeCompare(b.id),
    );
    const projectId = sorted[0]?.project ?? null;
    const container = projectId ?? `harness:${sorted[0]?.harness ?? "unknown"}`;
    const tokens = sorted.reduce((sum, file) => sum + (file.metrics.tokens?.o200k ?? 0), 0);
    const neverRead = sorted.filter((file) => file.neverRead === true).length;
    const where = `invisible from ${displayNameOf(index, projectId)}`;
    const readNote = sorted.some((file) => file.readSignal.source === "transcript-tool-use")
      ? `; ${plural(neverRead, "fact")} never read`
      : "";
    const flags: Flag[] = ["memory"];
    out.push({
      id: `finding:shadow-memory:${sorted[0]?.id ?? unit}`,
      category: "shadow-memory",
      severity: "medium",
      container,
      targets: sorted.map((file) => ({ id: file.id, role: "subject" as const, preselect: false })),
      message: `1 memory unit (${plural(sorted.length, "file")}, ${tokens} tokens) kept under ${harnessNameOf(index, sorted[0]?.harness ?? null)}'s user scope, ${where}${readNote}`,
      evidence: [
        {
          kind: "loading-rule",
          detail: `auto-memory unit ${unit} lives under the harness's user scope, not in the repository`,
        },
      ],
      confidence: "certain",
      impact: {
        bytes: sorted.reduce((sum, file) => sum + file.metrics.bytes, 0),
        tokens,
        files: sorted.length,
      },
      flags,
      action: { kind: "clean", preselect: false, locator: null },
    });
  }
  return out;
}

function duplicateFindings(index: Index): Finding[] {
  const entityById = new Map(index.entities.map((entity) => [entity.id, entity]));
  const groups = new Map<string, { members: Set<string>; same: string }>();
  const groupOf = new Map<string, string>();
  for (const edge of index.edges) {
    if (edge.kind !== "duplicates") continue;
    const key = groupOf.get(edge.from) ?? groupOf.get(edge.to) ?? `${edge.same}:${edge.from}`;
    const group = groups.get(key) ?? { members: new Set<string>(), same: edge.same };
    group.members.add(edge.from);
    group.members.add(edge.to);
    groups.set(key, group);
    groupOf.set(edge.from, key);
    groupOf.set(edge.to, key);
  }
  const out: Finding[] = [];
  for (const [, group] of groups) {
    const members = [...group.members]
      .map((id) => entityById.get(id))
      .filter((entity): entity is Entity => entity !== undefined)
      .toSorted((a, b) => a.id.localeCompare(b.id));
    const subject = members[0];
    if (subject === undefined) continue;
    const label = subject.kind === "mcp-server" ? `MCP server ${subject.label}` : subject.label;
    const places = members.map(
      (entity) =>
        `${entity.scope} scope${entity.project === null ? "" : ` of ${displayNameOf(index, entity.project)}`}`,
    );
    const flags: Flag[] = [];
    if (members.some((entity) => entity.shared === true)) flags.push("shared");
    if (members.some((entity) => entity.sensitive)) flags.push("sensitive");
    out.push({
      id: `finding:duplicate:${subject.id}`,
      category: "duplicate",
      severity: "low",
      container: subject.project ?? `harness:${subject.harness ?? "unknown"}`,
      targets: members.map((entity, i) => ({
        id: entity.id,
        role: i === 0 ? ("subject" as const) : ("counterpart" as const),
      })),
      message:
        group.same === "content"
          ? `${label} has the same content as ${members
              .slice(1)
              .map((entity) => entity.label)
              .join(", ")}`
          : `${label} is configured ${members.length} times with the same ${group.same} (${[...new Set(places)].join(", ")})`,
      evidence: [
        {
          kind: group.same === "content" ? "content-hash" : "endpoint",
          detail:
            group.same === "endpoint" && subject.kind === "mcp-server"
              ? subject.endpointKey
              : "identical bytes",
        },
      ],
      confidence: group.same === "content" ? "certain" : "high",
      impact: {
        bytes: members.slice(1).reduce((sum, entity) => sum + entity.metrics.bytes, 0),
        tokens: null,
        files: members.slice(1).reduce((sum, entity) => sum + (entity.metrics.files ?? 0), 0),
      },
      flags,
      action: { kind: "open", preselect: false, locator: subject.locator },
    });
  }
  return out;
}

function headlineOf(index: Index, focusId: string | undefined): Headline {
  let focus: Headline["focus"];
  if (focusId !== undefined && index.projects.some((project) => project.id === focusId)) {
    const enclosing = index.projects.find(
      (project) => project.id === focusId && project.enclosesCwd,
    );
    focus = { project: focusId, reason: enclosing === undefined ? "most-expensive" : "cwd" };
  } else {
    const cwdProject = index.projects.find((project) => project.enclosesCwd);
    if (cwdProject !== undefined) {
      focus = { project: cwdProject.id, reason: "cwd" };
    } else {
      const costOf = (projectId: string): number =>
        index.projects.find((project) => project.id === projectId)?.perHarness === undefined
          ? 0
          : Object.values(
              index.projects.find((project) => project.id === projectId)?.perHarness ?? {},
            ).reduce((sum, item) => sum + (item?.sessionLoad.tokens ?? 0), 0);
      const most = index.projects
        .filter((project) => project.reachability === "present")
        .toSorted((a, b) => costOf(b.id) - costOf(a.id) || a.id.localeCompare(b.id))[0];
      focus =
        most === undefined
          ? { project: null, reason: "none" }
          : { project: most.id, reason: "most-expensive" };
    }
  }
  const focused =
    focus.project === null
      ? undefined
      : index.projects.find((project) => project.id === focus.project);
  const perHarness: Headline["perHarness"] = index.harnesses.map((harness) => {
    const multiplier = multiplierFor(harness.modelFamily);
    const baseline: TokenRange = applyMultiplier(harness.userScope.baseline.tokens, multiplier);
    const projectTokens = focused?.perHarness[harness.harness]?.sessionLoad.tokens ?? 0;
    const project: TokenRange = applyMultiplier(projectTokens, multiplier);
    const total = addRanges(baseline, project);
    return {
      harness: harness.harness,
      modelFamily: harness.modelFamily,
      contextWindowTokens: harness.contextWindowTokens,
      baseline,
      project,
      total,
      pctOfContext:
        harness.contextWindowTokens === null || harness.contextWindowTokens === 0
          ? null
          : Math.round((total.mid / harness.contextWindowTokens) * 1000) / 10,
    };
  });
  return { scope: "user-controllable", focus, perHarness };
}

export async function audit(scanned: Index, options: AuditOptions = {}): Promise<AuditIndex> {
  const index: Index =
    options.readSignal === false
      ? {
          ...scanned,
          warnings: [
            ...scanned.warnings,
            warning(
              "read-signal-skipped",
              "memory read signal not computed: never-read facts are unknown",
              null,
              null,
              "skipped",
            ),
          ],
        }
      : await withReadSignal(scanned);
  const findings = [
    ...orphanFindings(index),
    ...harnessCacheFindings(index),
    ...shadowMemoryFindings(index),
    ...duplicateFindings(index),
  ].toSorted(byCategoryThenTarget);
  return { ...index, findings, headline: headlineOf(index, options.focus) };
}
