/**
 * §7.8 autogenerated [D8; D82]: a context file carrying the fingerprints of a harness's `/init`
 * template rather than a human's failure patterns. One matched phrase → confidence `medium`, two
 * or more → `high`; severity is `low` and the action is `open` either way — the file is the
 * user's to keep or to rewrite, and moldig only says where it came from.
 *
 * Memory files and skills are never candidates, and neither is a `local` context file: the
 * templates of §7.8 are all generated as the shared, project-scoped file.
 */
import type { ContextFile, Finding, Index } from "../index/types.js";
import { readText } from "../scan/fs.js";
import { matchFingerprints } from "./fingerprints.js";
import { containerOf, flagsOf } from "./shared.js";

function isCandidate(entity: ContextFile): boolean {
  return entity.form === "context" || entity.form === "instructions" || entity.form === "rule";
}

export async function autogeneratedFindings(index: Index): Promise<Finding[]> {
  const files = index.entities.filter(
    (entity): entity is ContextFile => entity.kind === "context-file" && isCandidate(entity),
  );
  const out: Finding[] = [];
  for (const entity of files) {
    // oxlint-disable-next-line no-await-in-loop -- one bounded read per candidate, in id order
    const raw = await readText(entity.path);
    if (raw === null) continue;
    const matches = matchFingerprints(raw);
    const first = matches[0];
    if (first === undefined) continue;
    const { harnessName, template } = first.fingerprint;
    out.push({
      id: `finding:autogenerated:${entity.id}`,
      category: "autogenerated",
      severity: "low",
      container: containerOf(entity),
      targets: [{ id: entity.id, role: "subject" }],
      message: `${entity.label} carries the ${harnessName} ${template} template rather than hand-written guidance`,
      evidence: matches.map((match) => ({
        kind: "fingerprint",
        detail: `${match.fingerprint.harnessName} ${match.fingerprint.template}: "${match.phrase}"`,
      })),
      confidence: matches.length >= 2 ? "high" : "medium",
      impact: {
        bytes: entity.metrics.bytes,
        tokens: entity.metrics.tokens?.o200k ?? null,
        files: 1,
      },
      flags: flagsOf([entity]),
      action: { kind: "open", preselect: false, locator: entity.locator },
    });
  }
  return out;
}
