/**
 * The eight categories over a real tree. The `claude-code/breadcrumbs` case is copied into a temp
 * directory (never the real home, never the committed fixture) and three things a scan cannot
 * invent are planted in the copy before the scan runs: a context file long enough to cost a
 * session real tokens, one carrying Claude Code's `/init` line, and an MCP entry holding a
 * literal secret. Everything else — duplicate, orphan, shadow-memory, harness-cache — the case
 * already carries.
 */
import { readFile, writeFile } from "node:fs/promises";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { audit, scan } from "../index.js";
import type { AuditIndex, Category, Finding, Index } from "../index/types.js";
import { isRecord, readJsonObject } from "../scan/fs.js";
import { loadFixture, type FixtureTree } from "../testing/index.js";
import { compareForDisplay } from "./order.js";

const NOW = new Date("2026-08-26T12:00:00.000Z");
const PLATFORM = "darwin";
/** Verbatim from Claude Code's `/init` template; the phrase the autogenerated table ships. */
const INIT_LINE =
  "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.";
/** A value the exposure finding must never repeat back, in any field. */
const SECRET = "sk-live-4f3a2b1c0d9e8f7a6b5c4d3e";

let tree: FixtureTree;
let scanned: Index;
let result: AuditIndex;

/** ~4,000 o200k tokens of ordinary prose: enough to cross the 2,000-token bloat threshold. */
function filler(sentences: number): string {
  let out = "";
  for (let n = 0; n < sentences; n += 1)
    out += `\n## Section ${n}\n\nThe build script for module ${n} lives under packages and its tests sit beside it, checked on every push and reviewed by whoever owns that area of the repository.\n`;
  return out;
}

function of(findings: Finding[], category: Category): Finding[] {
  return findings.filter((finding) => finding.category === category);
}

beforeAll(async () => {
  tree = await loadFixture("claude-code/breadcrumbs", {
    cwd: "root/project-a",
    now: NOW,
    platform: PLATFORM,
  });
  const bloated = tree.path("root/project-a/CLAUDE.md");
  await writeFile(bloated, (await readFile(bloated, "utf8")) + filler(120), "utf8");
  const generated = tree.path("root/project-a/apps/web/CLAUDE.md");
  await writeFile(
    generated,
    `# CLAUDE.md\n\n${INIT_LINE}\n\n${await readFile(generated, "utf8")}`,
    "utf8",
  );
  const mcp = tree.path("root/project-a/.mcp.json");
  const document = await readJsonObject(mcp);
  const servers = document?.["mcpServers"];
  if (document === null || !isRecord(servers))
    throw new Error("the case's .mcp.json changed shape");
  servers["server-secret"] = {
    type: "http",
    url: "https://mcp.example.com/mcp",
    headers: { Authorization: `Bearer ${SECRET}` },
  };
  await writeFile(mcp, JSON.stringify({ ...document, mcpServers: servers }, null, 2), "utf8");

  scanned = await scan({
    home: tree.home,
    roots: tree.roots,
    cwd: tree.cwd,
    platform: PLATFORM,
    env: tree.env,
    git: false,
    now: NOW,
  });
  result = await audit(scanned);
});

afterAll(async () => {
  await tree.cleanup();
});

describe("the eight categories over claude-code/breadcrumbs", () => {
  it("files bloat for the context file that costs a session real tokens, and proposes only open", () => {
    const findings = of(result.findings, "bloat");
    expect(findings.length).toBeGreaterThanOrEqual(1);
    const finding = findings[0];
    expect(finding?.severity).toBe("medium");
    expect(finding?.impact.tokens).toBeGreaterThanOrEqual(2000);
    expect(finding?.message).toMatch(/costs \d+ tokens in every Claude Code session$/);
    expect(finding?.evidence.map((item) => item.kind)).toEqual(["loading-rule", "token-count"]);
    expect(finding?.confidence).toBe("certain");
    // Bloat is advice: no category of finding may propose removing a human-owned file.
    for (const row of findings) {
      expect(row.action.kind).toBe("open");
      expect(row.action.preselect).toBe(false);
      expect(row.targets.every((target) => target.preselect !== true)).toBe(true);
    }
  });

  it("files autogenerated for the file carrying the /init line, with the phrase as evidence", () => {
    const finding = of(result.findings, "autogenerated")[0];
    expect(finding?.severity).toBe("low");
    expect(finding?.confidence).toBe("medium");
    expect(finding?.message).toBe(
      "apps/web/CLAUDE.md carries the Claude Code /init template rather than hand-written guidance",
    );
    expect(finding?.evidence).toEqual([
      { kind: "fingerprint", detail: `Claude Code /init: "${INIT_LINE}"` },
    ]);
    expect(finding?.action.kind).toBe("open");
  });

  it("files exposure for the literal secret and never repeats its value", () => {
    const finding = of(result.findings, "exposure")[0];
    expect(finding?.severity).toBe("high");
    expect(finding?.flags).toContain("secret-exposed");
    expect(finding?.message).toBe(
      "server-secret carries an Authorization header in a world-readable .mcp.json",
    );
    expect(finding?.evidence[0]).toEqual({ kind: "secret-key", detail: "headers.Authorization" });
    expect(JSON.stringify(finding)).not.toContain(SECRET);
    expect(JSON.stringify(finding)).not.toContain("Bearer");
    // Nothing anywhere in the audited document carries the value either.
    expect(JSON.stringify(result)).not.toContain(SECRET);
  });

  it("files duplicate for the MCP servers configured twice, and never for a context file", () => {
    const findings = of(result.findings, "duplicate");
    expect(findings.length).toBeGreaterThanOrEqual(1);
    for (const finding of findings) {
      expect(finding.severity).toBe("low");
      expect(finding.action.kind).toBe("open");
      const subject = result.entities.find((entity) => entity.id === finding.targets[0]?.id);
      expect(subject?.kind).toBe("mcp-server");
    }
  });

  it("files orphan for the Project whose directory is gone, cleaning its memory", () => {
    const finding = of(result.findings, "orphan").find((row) =>
      row.message.includes("directory gone"),
    );
    expect(finding?.severity).toBe("medium");
    expect(finding?.confidence).toBe("certain");
    expect(finding?.action.kind).toBe("clean");
    expect(finding?.flags).toContain("memory");
    expect(finding?.evidence[0]?.kind).toBe("path-missing");
  });

  it("files shadow-memory per unit, never preselected", () => {
    const findings = of(result.findings, "shadow-memory");
    expect(findings.length).toBeGreaterThanOrEqual(1);
    for (const finding of findings) {
      expect(finding.flags).toContain("memory");
      expect(finding.action.preselect).toBe(false);
      expect(finding.targets.every((target) => target.preselect === false)).toBe(true);
      expect(finding.message).toMatch(/^1 memory unit \(/);
    }
  });

  it("files harness-cache per container and cacheKind, low below 100 MB and 50 units", () => {
    const findings = of(result.findings, "harness-cache");
    expect(findings.length).toBeGreaterThanOrEqual(1);
    for (const finding of findings) {
      expect(finding.severity).toBe("low");
      expect(finding.action.kind).toBe("clean");
      expect(finding.evidence[0]?.kind).toBe("retention-rule");
      for (const target of finding.targets) {
        const unit = result.entities.find((entity) => entity.id === target.id);
        expect(unit?.kind === "harness-cache" && unit.rule).not.toBe("kept");
      }
    }
  });

  it("covers seven of the eight categories over this tree — drift needs a lock hash no fixture records", () => {
    const seen = new Set(result.findings.map((finding) => finding.category));
    expect([...seen].toSorted()).toEqual([
      "autogenerated",
      "bloat",
      "duplicate",
      "exposure",
      "harness-cache",
      "orphan",
      "shadow-memory",
    ]);
  });
});

describe("the audited document", () => {
  it("serialises identically on two runs of one scan", async () => {
    const again = await audit(scanned);
    expect(JSON.stringify(again.findings)).toBe(JSON.stringify(result.findings));
    expect(JSON.stringify(again.headline)).toBe(JSON.stringify(result.headline));
  });

  it("serialises findings by category, first target id and id", () => {
    const keys = result.findings.map(
      (finding) => `${finding.category} ${finding.targets[0]?.id ?? ""} ${finding.id}`,
    );
    expect(keys).toEqual([...keys].toSorted());
  });

  it("renders in the glossary's category order, pinned findings first inside each", () => {
    const order: Category[] = [
      "duplicate",
      "orphan",
      "bloat",
      "drift",
      "shadow-memory",
      "autogenerated",
      "harness-cache",
      "exposure",
    ];
    const displayed = result.findings.toSorted(compareForDisplay);
    const ranks = displayed.map((finding) => order.indexOf(finding.category));
    expect(ranks).toEqual([...ranks].toSorted((a, b) => a - b));
    for (const category of order) {
      const rows = displayed.filter((finding) => finding.category === category);
      const pinned = rows.map((finding) => (finding.flags.length > 0 ? 0 : 1));
      expect(pinned).toEqual([...pinned].toSorted((a, b) => a - b));
    }
  });

  it("gives every finding a mandatory severity badge and a container", () => {
    for (const finding of result.findings) {
      expect(["low", "medium", "high"]).toContain(finding.severity);
      expect(finding.container).not.toBe("");
      expect(finding.targets.length).toBeGreaterThan(0);
    }
  });

  it("--no-read-signal appends exactly one warning and claims no never-read verdict", async () => {
    const skipped = await audit(scanned, { readSignal: false });
    expect(skipped.warnings.filter((warning) => warning.code === "read-signal-skipped")).toEqual([
      {
        code: "read-signal-skipped",
        message: "memory read signal not computed: never-read facts are unknown",
        harness: null,
        path: null,
        effect: "skipped",
      },
    ]);
    const memory = skipped.entities.filter((entity) => entity.kind === "memory-file");
    expect(memory.length).toBeGreaterThan(0);
    for (const file of memory) {
      expect(file.kind === "memory-file" && file.readSignal.source).toBe("not-computed");
      expect(file.kind === "memory-file" && file.neverRead).toBeNull();
    }
    // The shadow-memory message drops its read note when no signal was computed.
    for (const finding of of(skipped.findings, "shadow-memory"))
      expect(finding.message).not.toContain("never read");
  });
});
