/**
 * The two orders of §7.1, both named [D85].
 *
 * The **serialised** order is what `findings[]` carries in `audit --json`: `(category, first
 * target id, id)` with plain string comparison, so two audits of one machine serialise byte for
 * byte identically whatever the locale.
 *
 * The **display** order is what a report shows: the glossary's category sequence, then the
 * findings carrying any pinned flag, then `impact.bytes` descending, ties broken by the
 * serialised order. The CLI and the TUI import `compareForDisplay` rather than each keeping a
 * category table of their own.
 */
import type { Category, Finding, Flag } from "../index/types.js";

/** CONTEXT.md's Category order, which the report's rows and the category labels both follow. */
export const CATEGORY_ORDER: readonly Category[] = [
  "duplicate",
  "orphan",
  "bloat",
  "drift",
  "shadow-memory",
  "autogenerated",
  "harness-cache",
  "exposure",
];

/** §7.1: all six flags are delicate enough to pin their finding to the top of its category. */
export const PINNED_FLAGS: readonly Flag[] = [
  "shared",
  "sensitive",
  "secret-exposed",
  "memory",
  "live",
  "user-content",
];

function compareStrings(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** The order `findings[]` is serialised in: `(category, first target id, id)` [07 Answer]. */
export function compareSerialised(a: Finding, b: Finding): number {
  return (
    compareStrings(a.category, b.category) ||
    compareStrings(a.targets[0]?.id ?? "", b.targets[0]?.id ?? "") ||
    compareStrings(a.id, b.id)
  );
}

function categoryRank(finding: Finding): number {
  const rank = CATEGORY_ORDER.indexOf(finding.category);
  return rank === -1 ? CATEGORY_ORDER.length : rank;
}

function isPinned(finding: Finding): boolean {
  return finding.flags.some((flag) => PINNED_FLAGS.includes(flag));
}

/** The order a report renders in: category → pinned flags → `impact.bytes` desc → serialised. */
export function compareForDisplay(a: Finding, b: Finding): number {
  return (
    categoryRank(a) - categoryRank(b) ||
    Number(isPinned(b)) - Number(isPinned(a)) ||
    b.impact.bytes - a.impact.bytes ||
    compareSerialised(a, b)
  );
}
